# Generated by Django 2.1.7 on 2019-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
                ('upload_time', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
