# Generated by Django 2.1.7 on 2019-08-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='describe',
            field=models.TextField(default='DataFlair Django tutorials'),
        ),
    ]
