version: "2"

networks:
  ineuron:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ineuron
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "./kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - ineuron
  pyspark:
    image: avnish327030/pyspark-3.2.1:latest
    ports:
      - "4040:4040"
      - "4041:4041"
      - "4042:4042"
    volumes:
      - "./pyspark_data:/project"
    networks:
      - ineuron

  cassandra:
    image: docker.io/bitnami/cassandra:4.1
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - './cassandra_data:/bitnami'
    environment:
      - "CASSANDRA_CLUSTER_NAME=cassandra-cluster"
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - ineuron